$ANSIBLE_VAULT;1.1;AES256
38303233336361396162393664626264353130373463326638316635653531346665666361613766
6338353034613739616638303763373065386165346636360a353436343561626630376162386339
32346533653431353130653362383066353863356332343663396232356630613833663734643363
6239386563383165320a653637343538386363626163656636386432633335323164386566613835
66363234653464633735663031316636333133623834313634396262383261333165
