---
- name: Show SELinux
  hosts: all
  become: true

  tasks:
    - name: Install required packages
      ansible.builtin.yum:
        name: policycoreutils-python-utils
        state: present

    - name: Set SELinux context
      sefcontext:
        target: /tmp/removeme
        setype: public_content_rw_t
        state: present
      notify:
        - Run restorecon

  handlers:
    - name: Run restorecon
      ansible.builtin.command:
        cmd: restorecon -v /tmp/removeme

